# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bifox/research/geant4/PositionElectronTomographySimulation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bifox/research/geant4/PositionElectronTomographySimulation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bifox/research/geant4/PositionElectronTomographySimulation/CMakeFiles /home/bifox/research/geant4/PositionElectronTomographySimulation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bifox/research/geant4/PositionElectronTomographySimulation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PETSim

# Build rule for target.
PETSim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PETSim
.PHONY : PETSim

# fast build rule for target.
PETSim/fast:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/build
.PHONY : PETSim/fast

PETmain.o: PETmain.cc.o

.PHONY : PETmain.o

# target to build an object file
PETmain.cc.o:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/PETmain.cc.o
.PHONY : PETmain.cc.o

PETmain.i: PETmain.cc.i

.PHONY : PETmain.i

# target to preprocess a source file
PETmain.cc.i:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/PETmain.cc.i
.PHONY : PETmain.cc.i

PETmain.s: PETmain.cc.s

.PHONY : PETmain.s

# target to generate assembly for a file
PETmain.cc.s:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/PETmain.cc.s
.PHONY : PETmain.cc.s

src/PETActionInitialization.o: src/PETActionInitialization.cc.o

.PHONY : src/PETActionInitialization.o

# target to build an object file
src/PETActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETActionInitialization.cc.o
.PHONY : src/PETActionInitialization.cc.o

src/PETActionInitialization.i: src/PETActionInitialization.cc.i

.PHONY : src/PETActionInitialization.i

# target to preprocess a source file
src/PETActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETActionInitialization.cc.i
.PHONY : src/PETActionInitialization.cc.i

src/PETActionInitialization.s: src/PETActionInitialization.cc.s

.PHONY : src/PETActionInitialization.s

# target to generate assembly for a file
src/PETActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETActionInitialization.cc.s
.PHONY : src/PETActionInitialization.cc.s

src/PETDetectorConstruction.o: src/PETDetectorConstruction.cc.o

.PHONY : src/PETDetectorConstruction.o

# target to build an object file
src/PETDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETDetectorConstruction.cc.o
.PHONY : src/PETDetectorConstruction.cc.o

src/PETDetectorConstruction.i: src/PETDetectorConstruction.cc.i

.PHONY : src/PETDetectorConstruction.i

# target to preprocess a source file
src/PETDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETDetectorConstruction.cc.i
.PHONY : src/PETDetectorConstruction.cc.i

src/PETDetectorConstruction.s: src/PETDetectorConstruction.cc.s

.PHONY : src/PETDetectorConstruction.s

# target to generate assembly for a file
src/PETDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETDetectorConstruction.cc.s
.PHONY : src/PETDetectorConstruction.cc.s

src/PETDetectorMessenger.o: src/PETDetectorMessenger.cc.o

.PHONY : src/PETDetectorMessenger.o

# target to build an object file
src/PETDetectorMessenger.cc.o:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETDetectorMessenger.cc.o
.PHONY : src/PETDetectorMessenger.cc.o

src/PETDetectorMessenger.i: src/PETDetectorMessenger.cc.i

.PHONY : src/PETDetectorMessenger.i

# target to preprocess a source file
src/PETDetectorMessenger.cc.i:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETDetectorMessenger.cc.i
.PHONY : src/PETDetectorMessenger.cc.i

src/PETDetectorMessenger.s: src/PETDetectorMessenger.cc.s

.PHONY : src/PETDetectorMessenger.s

# target to generate assembly for a file
src/PETDetectorMessenger.cc.s:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETDetectorMessenger.cc.s
.PHONY : src/PETDetectorMessenger.cc.s

src/PETEventAction.o: src/PETEventAction.cc.o

.PHONY : src/PETEventAction.o

# target to build an object file
src/PETEventAction.cc.o:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETEventAction.cc.o
.PHONY : src/PETEventAction.cc.o

src/PETEventAction.i: src/PETEventAction.cc.i

.PHONY : src/PETEventAction.i

# target to preprocess a source file
src/PETEventAction.cc.i:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETEventAction.cc.i
.PHONY : src/PETEventAction.cc.i

src/PETEventAction.s: src/PETEventAction.cc.s

.PHONY : src/PETEventAction.s

# target to generate assembly for a file
src/PETEventAction.cc.s:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETEventAction.cc.s
.PHONY : src/PETEventAction.cc.s

src/PETPhysicsList.o: src/PETPhysicsList.cc.o

.PHONY : src/PETPhysicsList.o

# target to build an object file
src/PETPhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETPhysicsList.cc.o
.PHONY : src/PETPhysicsList.cc.o

src/PETPhysicsList.i: src/PETPhysicsList.cc.i

.PHONY : src/PETPhysicsList.i

# target to preprocess a source file
src/PETPhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETPhysicsList.cc.i
.PHONY : src/PETPhysicsList.cc.i

src/PETPhysicsList.s: src/PETPhysicsList.cc.s

.PHONY : src/PETPhysicsList.s

# target to generate assembly for a file
src/PETPhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETPhysicsList.cc.s
.PHONY : src/PETPhysicsList.cc.s

src/PETPrimaryGeneratorAction.o: src/PETPrimaryGeneratorAction.cc.o

.PHONY : src/PETPrimaryGeneratorAction.o

# target to build an object file
src/PETPrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETPrimaryGeneratorAction.cc.o
.PHONY : src/PETPrimaryGeneratorAction.cc.o

src/PETPrimaryGeneratorAction.i: src/PETPrimaryGeneratorAction.cc.i

.PHONY : src/PETPrimaryGeneratorAction.i

# target to preprocess a source file
src/PETPrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETPrimaryGeneratorAction.cc.i
.PHONY : src/PETPrimaryGeneratorAction.cc.i

src/PETPrimaryGeneratorAction.s: src/PETPrimaryGeneratorAction.cc.s

.PHONY : src/PETPrimaryGeneratorAction.s

# target to generate assembly for a file
src/PETPrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETPrimaryGeneratorAction.cc.s
.PHONY : src/PETPrimaryGeneratorAction.cc.s

src/PETRunAction.o: src/PETRunAction.cc.o

.PHONY : src/PETRunAction.o

# target to build an object file
src/PETRunAction.cc.o:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETRunAction.cc.o
.PHONY : src/PETRunAction.cc.o

src/PETRunAction.i: src/PETRunAction.cc.i

.PHONY : src/PETRunAction.i

# target to preprocess a source file
src/PETRunAction.cc.i:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETRunAction.cc.i
.PHONY : src/PETRunAction.cc.i

src/PETRunAction.s: src/PETRunAction.cc.s

.PHONY : src/PETRunAction.s

# target to generate assembly for a file
src/PETRunAction.cc.s:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETRunAction.cc.s
.PHONY : src/PETRunAction.cc.s

src/PETSteppingAction.o: src/PETSteppingAction.cc.o

.PHONY : src/PETSteppingAction.o

# target to build an object file
src/PETSteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETSteppingAction.cc.o
.PHONY : src/PETSteppingAction.cc.o

src/PETSteppingAction.i: src/PETSteppingAction.cc.i

.PHONY : src/PETSteppingAction.i

# target to preprocess a source file
src/PETSteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETSteppingAction.cc.i
.PHONY : src/PETSteppingAction.cc.i

src/PETSteppingAction.s: src/PETSteppingAction.cc.s

.PHONY : src/PETSteppingAction.s

# target to generate assembly for a file
src/PETSteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETSteppingAction.cc.s
.PHONY : src/PETSteppingAction.cc.s

src/PETTrackerHit.o: src/PETTrackerHit.cc.o

.PHONY : src/PETTrackerHit.o

# target to build an object file
src/PETTrackerHit.cc.o:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETTrackerHit.cc.o
.PHONY : src/PETTrackerHit.cc.o

src/PETTrackerHit.i: src/PETTrackerHit.cc.i

.PHONY : src/PETTrackerHit.i

# target to preprocess a source file
src/PETTrackerHit.cc.i:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETTrackerHit.cc.i
.PHONY : src/PETTrackerHit.cc.i

src/PETTrackerHit.s: src/PETTrackerHit.cc.s

.PHONY : src/PETTrackerHit.s

# target to generate assembly for a file
src/PETTrackerHit.cc.s:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETTrackerHit.cc.s
.PHONY : src/PETTrackerHit.cc.s

src/PETTrackerSD.o: src/PETTrackerSD.cc.o

.PHONY : src/PETTrackerSD.o

# target to build an object file
src/PETTrackerSD.cc.o:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETTrackerSD.cc.o
.PHONY : src/PETTrackerSD.cc.o

src/PETTrackerSD.i: src/PETTrackerSD.cc.i

.PHONY : src/PETTrackerSD.i

# target to preprocess a source file
src/PETTrackerSD.cc.i:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETTrackerSD.cc.i
.PHONY : src/PETTrackerSD.cc.i

src/PETTrackerSD.s: src/PETTrackerSD.cc.s

.PHONY : src/PETTrackerSD.s

# target to generate assembly for a file
src/PETTrackerSD.cc.s:
	$(MAKE) -f CMakeFiles/PETSim.dir/build.make CMakeFiles/PETSim.dir/src/PETTrackerSD.cc.s
.PHONY : src/PETTrackerSD.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... PETSim"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... PETmain.o"
	@echo "... PETmain.i"
	@echo "... PETmain.s"
	@echo "... src/PETActionInitialization.o"
	@echo "... src/PETActionInitialization.i"
	@echo "... src/PETActionInitialization.s"
	@echo "... src/PETDetectorConstruction.o"
	@echo "... src/PETDetectorConstruction.i"
	@echo "... src/PETDetectorConstruction.s"
	@echo "... src/PETDetectorMessenger.o"
	@echo "... src/PETDetectorMessenger.i"
	@echo "... src/PETDetectorMessenger.s"
	@echo "... src/PETEventAction.o"
	@echo "... src/PETEventAction.i"
	@echo "... src/PETEventAction.s"
	@echo "... src/PETPhysicsList.o"
	@echo "... src/PETPhysicsList.i"
	@echo "... src/PETPhysicsList.s"
	@echo "... src/PETPrimaryGeneratorAction.o"
	@echo "... src/PETPrimaryGeneratorAction.i"
	@echo "... src/PETPrimaryGeneratorAction.s"
	@echo "... src/PETRunAction.o"
	@echo "... src/PETRunAction.i"
	@echo "... src/PETRunAction.s"
	@echo "... src/PETSteppingAction.o"
	@echo "... src/PETSteppingAction.i"
	@echo "... src/PETSteppingAction.s"
	@echo "... src/PETTrackerHit.o"
	@echo "... src/PETTrackerHit.i"
	@echo "... src/PETTrackerHit.s"
	@echo "... src/PETTrackerSD.o"
	@echo "... src/PETTrackerSD.i"
	@echo "... src/PETTrackerSD.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

